name: graphene_server
description: A GraphQL inspired server and BSON based Schema.
version: 0.1.9+20
repository: https://github.com/LiveUser/graphene_server

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  compute: ^1.0.2
  power_plant: ^1.0.2+3
  objective_db: ^0.3.1+25
  bson: ^5.0.8
  mimalo: ^0.0.6+7

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
